#!/usr/bin/env python3
"""Generate the AppStream sidecar of every GUI package from its recipe.

The GNOME Software plugin for Stapler matches an application to a package with
`appstream_app_id == '<id>'` and looks for its icon at
`/var/cache/stplr/repo/<repo>/<package>/<id>.{svg,png}` — that is, next to the
Staplerfile. Without the ID nothing matches at all, so every GUI package needs
one, together with the metainfo document that describes it.

Writing those documents by hand would let them drift from the recipe, which
already carries the name, both summaries, both descriptions, the homepage and
the licence. They are generated from it instead, and validate_repo.py checks
that what is committed is what the recipe produces.
"""

from __future__ import annotations

import re
import shlex
import sys
from pathlib import Path
from urllib.parse import urlsplit
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[2]
MARKER = "Generated by .github/tools/sync_appstream.py"

# group= in the recipe is an RPM group; AppStream wants freedesktop categories.
CATEGORIES = {
    "Video/Players": ("AudioVideo", "Video"),
    "Networking/Instant messaging": ("Network", "InstantMessaging"),
    "Networking/Other": ("Network",),
    "Networking/Remote access": ("Network", "RemoteAccess"),
    "System/Configuration/Hardware": ("System",),
    "System/Configuration/Other": ("System",),
    "Development/Tools": ("Development",),
    "Games/Other": ("Game",),
    "Sound/Players": ("AudioVideo", "Audio"),
    "Office/Other": ("Office",),
}


def scalar(text: str, field: str) -> str | None:
    match = re.search(
        rf"^{re.escape(field)}=(?:'([^']*)'|\"([^\"]*)\"|([^#\n]+))",
        text,
        re.MULTILINE,
    )
    if not match:
        return None
    return next(value.strip() for value in match.groups() if value is not None)


def block(text: str, field: str) -> str | None:
    """Read a field written as a shell here-string across several lines."""
    match = re.search(rf"^{re.escape(field)}='((?:[^']|\n)*)'", text, re.MULTILINE)
    return match.group(1).strip() if match else None


def array(text: str, field: str) -> list[str]:
    match = re.search(rf"^{re.escape(field)}=\((.*?)\)", text, re.MULTILINE | re.DOTALL)
    if not match:
        return []
    try:
        return shlex.split(match.group(1), comments=True, posix=True)
    except ValueError:
        return []


def paragraphs(value: str) -> list[str]:
    return [" ".join(part.split()) for part in value.split("\n\n") if part.strip()]


def render(package: str, text: str) -> str | None:
    app_id = scalar(text, "appstream_app_id")
    if not app_id:
        return None

    display = scalar(text, "appstream_name") or scalar(text, "name") or package
    homepage = scalar(text, "homepage") or ""
    # maintainer is who packages it; GNOME Software shows who wrote the
    # application, so appstream_developer overrides it where they differ.
    maintainer = scalar(text, "maintainer") or ""
    developer = scalar(text, "appstream_developer") or ""
    if not developer:
        developer = re.sub(r"\s*<[^>]*>\s*", "", maintainer).strip() or "Nivora"
    licenses = array(text, "license") or ["LicenseRef-proprietary"]
    group = scalar(text, "group") or ""

    summary = block(text, "summary") or ""
    summary_ru = block(text, "summary_ru") or ""
    desc = block(text, "desc") or summary
    desc_ru = block(text, "desc_ru") or summary_ru

    # Always "<id>.desktop": an id may itself end in .desktop when that is
    # part of its reverse-DNS name, as with org.telegram.desktop.
    launchable = f"{app_id}.desktop"
    categories = CATEGORIES.get(group, ("Utility",))

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by .github/tools/sync_appstream.py from the recipe.",
        "     Edit the Staplerfile, then rerun the generator. -->",
        '<component type="desktop-application">',
        f"  <id>{escape(app_id)}</id>",
        f"  <launchable type=\"desktop-id\">{escape(launchable)}</launchable>",
        f"  <name>{escape(display)}</name>",
        f"  <summary>{escape(summary)}</summary>",
    ]
    if summary_ru:
        lines.append(f'  <summary xml:lang="ru">{escape(summary_ru)}</summary>')
    lines.append("  <description>")
    for para in paragraphs(desc):
        lines.append(f"    <p>{escape(para)}</p>")
    for para in paragraphs(desc_ru):
        lines.append(f'    <p xml:lang="ru">{escape(para)}</p>')
    lines.append("  </description>")
    lines.append(f"  <project_license>{escape(' AND '.join(licenses))}</project_license>")
    lines.append(f"  <metadata_license>MIT</metadata_license>")
    # The developer id must be a reverse-DNS ASCII string. Deriving it from a
    # human name produces something appstreamcli rejects outright — a Cyrillic
    # maintainer name turns into an invalid id — so it comes from the homepage
    # host, and is simply left out when no host is available.
    developer_id = ""
    parts = urlsplit(homepage)
    host = re.sub(r"^www\.", "", parts.hostname or "")
    if host in {"github.com", "gitlab.com"}:
        # Reversing the forge host would name the forge, not the project, so
        # the owner is used the way forge-hosted projects normally identify
        # themselves: io.github.<owner>.
        owner = parts.path.strip("/").split("/")[0].lower()
        prefix = "io.github" if host == "github.com" else "io.gitlab"
        if re.fullmatch(r"[a-z0-9-]+", owner):
            developer_id = f"{prefix}.{owner}"
    elif re.fullmatch(r"[a-z0-9.-]+", host) and "." in host:
        developer_id = ".".join(reversed(host.split(".")))
    if developer_id:
        lines.append(f'  <developer id="{escape(developer_id)}">')
    else:
        lines.append("  <developer>")
    lines.append(f"    <name>{escape(developer)}</name>")
    lines.append("  </developer>")
    if homepage:
        lines.append(f'  <url type="homepage">{escape(homepage)}</url>')
    lines.append("  <categories>")
    for category in categories:
        lines.append(f"    <category>{escape(category)}</category>")
    lines.append("  </categories>")
    # Nivora cannot vouch for what a repackaged application shows, so the
    # rating states the one thing that is always true of these packages.
    lines.append('  <content_rating type="oars-1.1"/>')
    lines.append("</component>")
    return "\n".join(lines) + "\n"


def main() -> int:
    check = "--check" in sys.argv
    stale: list[str] = []
    written = 0
    for recipe in sorted(ROOT.glob("*/Staplerfile")):
        package = recipe.parent.name
        text = recipe.read_text(encoding="utf-8")
        document = render(package, text)
        if document is None:
            continue
        app_id = scalar(text, "appstream_app_id")
        target = recipe.parent / f"{app_id}.metainfo.xml"
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if current is not None and MARKER not in current:
            # Upstream ships its own metainfo for this package. It says more
            # than the recipe can, so it is left exactly as it is.
            continue
        if current == document:
            continue
        if check:
            stale.append(f"{package}: {target.name} differs from the recipe")
            continue
        target.write_text(document, encoding="utf-8")
        written += 1
        print(f"написан {target.relative_to(ROOT)}")
    if check and stale:
        for line in stale:
            print(line, file=sys.stderr)
        return 1
    if not check:
        print(f"OK: обновлено документов: {written}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
